spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.146:8848

server:
  port: 10101

dubbo:
  application:
    name: provider
  registry:
    address: nacos://192.168.10.146:8848
  scan:
    basePackages: cn.nocer.alibaba.dubbo.provider.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
